version: '3'

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./db:/tmp/db:ro
      - ./db/init-user.sh:/docker-entrypoint-initdb.d/01-init-user.sh:ro
      - ./docker-compose/db-init-for-docker.sh:/docker-entrypoint-initdb.d/02-init.sh:ro
    ports:
      - "${ISUCON_8_DB_IP_PORT:-0.0.0.0:3306}:3306"

  app:
    image: node:8
    volumes:
      - ./webapp:/tmp/webapp
      - ./docker-compose/app-run.sh:/tmp/app-run.sh:ro
    depends_on:
      - db
    # FIXME: DBの準備完了を待つ（今はとりあえずrestartでごまかしている）
    restart: on-failure
    command: ["/tmp/app-run.sh"]
    ports:
      - "${ISUCON_8_APP_IP_PORT:-0.0.0.0:8080}:8080"
